# Generated by Django 5.0.6 on 2024-06-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
