# Generated by Django 5.0.6 on 2024-06-21 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_lesson_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='day',
        ),
        migrations.AddField(
            model_name='lesson',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='accounts.center'),
        ),
    ]
