# Generated by Django 5.0.6 on 2024-05-29 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dateslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='dateslot',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dateslot',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
