# Generated by Django 5.0.6 on 2024-06-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.ManyToManyField(blank=True, to='accounts.duration'),
        ),
    ]
