# Generated by Django 5.0.6 on 2024-05-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_center_student_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_center',
            field=models.BooleanField(default=False),
        ),
    ]
