# Generated by Django 5.0.6 on 2024-05-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_is_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_center',
        ),
    ]
