# Generated by Django 5.0.6 on 2024-06-02 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_lesson_subject_remove_lesson_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 7, 2)),
        ),
    ]
