# Generated by Django 5.0.6 on 2024-06-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_lesson_end_date'),
    ]

    operations = [
    ]
