# Generated by Django 5.0.6 on 2024-06-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student_lastname_student_phone_teacher_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
    ]
